## NumPy (Numerical Python) 
is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Numpy provides the powerful data structure known as n-d array and function to manipulate that n-d array .This data structure is used by other library to represent complex data such as images.

In [68]:
#Importing Numpy package
import numpy as np

## Creating Array
## 1-d Array
- arrays are Homogeneous(can only contain a single datatype)

In [69]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                        # Prints "[5, 2, 3]"
print("size of array :",a.size)        #number of elemnets
print("Dimention of aray :",a.ndim)    
print("Shape of the array :", a.shape)
print("Array Element Type :",a.dtype)


x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype) 

<class 'numpy.ndarray'>
1 2 3
[5 2 3]
size of array : 3
Dimention of aray : 1
Shape of the array : (3,)
Array Element Type : int32
int64


## n-d Array

In [70]:
#2d arrays are collection of 1d arrays

a = np.array([[5,7,12],[7,9,15]])
print(a)
print("Size of array :",a.size) #number of elemnets
print("Dimention of array :",a.ndim)
print("Shape of the array :", a.shape) # 2 elementin 2d, 3 element in 1d
print("Array Element Type :",a.dtype)

[[ 5  7 12]
 [ 7  9 15]]
Size of array : 6
Dimention of array : 2
Shape of the array : (2, 3)
Array Element Type : int32


In [71]:
# here we have 1 element in 3 dimension, 3 elementin 2d, 3 element in 1d

a = np.array([[[5,7,12],[7,9,15],[7,9,15]]])
print(a)
print("Size of array :",a.size)
print("Dimention of array :",a.ndim)
print("Shape of the array :", a.shape) # 1 element in 3 dimension, 3 elementin 2d, 3 element in 1d
print("Array Element Type :",a.dtype)

[[[ 5  7 12]
  [ 7  9 15]
  [ 7  9 15]]]
Size of array : 9
Dimention of array : 3
Shape of the array : (1, 3, 3)
Array Element Type : int32


## Predefined functions

In [72]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              
print('\n')
b = np.ones((1,2))    # Create an array of all ones
print(b)              
print('\n')
c = np.full((2,2), 7)  # Create a constant array
print(c)               

print('\n')
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              
                      
print('\n')
e = np.random.random((2,2))  # Create an array filled with random values, actually returns random nos b/w '0' and '1'
print(e)                     
                             
print('\n')
f = np.arange(6)
print(x)                     

print('\n')
g = np.arange(10,20)
print(g)

[[0. 0.]
 [0. 0.]]


[[1. 1.]]


[[7 7]
 [7 7]]


[[1. 0.]
 [0. 1.]]


[[0.50611914 0.25763501]
 [0.51638238 0.59036317]]


[1 2]


[10 11 12 13 14 15 16 17 18 19]


## np.linspace(start,end,no.of elements)
- linearly distributed space
- always gives you float array

In [73]:
print(np.linspace(10,50,5)) #5 linearly distributed space between 10 to 50

[10. 20. 30. 40. 50.]


## Random Numbers
- returns random numbers in b/n 0 and 1

In [74]:
np.random.rand()

0.8597119827316653

In [75]:
np.random.random()

0.4236041543775184

In [76]:
np.random.rand(5,3)*100

array([[13.63749464, 32.37845053, 24.57015692],
       [54.87777387, 40.09620409, 27.32587286],
       [70.73963545, 54.18131874, 44.92049513],
       [75.00992903, 68.22428138, 12.57819123],
       [70.76874055, 92.19561891, 40.55094121]])

In [77]:
np.random.randint(2,10) # to print any random number b/w 2 to 10

9

In [78]:
np.random.randint(3,20,6) # to print any 6 random numbers b/w 3 to 20 

array([ 4, 16, 18,  5, 15,  5])

In [79]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:3, 1:3]
print(b)
print('\n')
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1], then,
print('\n')
print(a[0, 1])   # Prints "77"

[[ 2  3]
 [ 6  7]
 [10 11]]


2


77


## Array Manipulation

## Dimensional
- Reshape
- Ravel

In [80]:
# Reshape
a = np.random.randint(50,100,24).reshape(4,6)
print(a)

[[64 51 69 54 92 98]
 [64 75 60 78 87 89]
 [74 76 92 91 66 69]
 [55 72 63 64 59 86]]


In [81]:
# Ravel - opposite of Reshape

a.ravel()

array([64, 51, 69, 54, 92, 98, 64, 75, 60, 78, 87, 89, 74, 76, 92, 91, 66,
       69, 55, 72, 63, 64, 59, 86])

In [82]:
a.ravel().reshape(6,4)

array([[64, 51, 69, 54],
       [92, 98, 64, 75],
       [60, 78, 87, 89],
       [74, 76, 92, 91],
       [66, 69, 55, 72],
       [63, 64, 59, 86]])

## Split
- horizontal 
- vertical

In [83]:
a = np.random.randint(10,50,24).reshape(4,6)
a

array([[33, 18, 13, 29, 40, 39],
       [42, 47, 24, 13, 34, 15],
       [37, 32, 36, 42, 11, 29],
       [28, 38, 26, 11, 17, 45]])

In [84]:
# horizontal
np.hsplit(a,3)

[array([[33, 18],
        [42, 47],
        [37, 32],
        [28, 38]]),
 array([[13, 29],
        [24, 13],
        [36, 42],
        [26, 11]]),
 array([[40, 39],
        [34, 15],
        [11, 29],
        [17, 45]])]

In [85]:
# vertical
np.vsplit(a,2)[1] # split and retreive the list of array
# it is spliting from the main file
#used during image processing etc.

array([[37, 32, 36, 42, 11, 29],
       [28, 38, 26, 11, 17, 45]])

## Stacking
- horizontal 
- vertical

In [86]:
a = np.arange(9).reshape(3,3)

b = np.arange(20,29).reshape(3,3)


In [87]:
np.vstack((a,b)) #Vertical Stacking

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [88]:
np.hstack((a,b)) #Horizontal Stacking

array([[ 0,  1,  2, 20, 21, 22],
       [ 3,  4,  5, 23, 24, 25],
       [ 6,  7,  8, 26, 27, 28]])